apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thingz
  namespace: thingz
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - thingz.example.com
      secretName: thingz-tls
  rules:
    - host: thingz.example.com
      http:
        paths:
          - path: /api/fo
            pathType: Prefix
            backend:
              service:
                name: thingz-backend
                port:
                  number: 8080
          - path: /oauth2
            pathType: Prefix
            backend:
              service:
                name: thingz-backend
                port:
                  number: 8080
          - path: /login/oauth2
            pathType: Prefix
            backend:
              service:
                name: thingz-backend
                port:
                  number: 8080
          - path: /actuator/health
            pathType: Exact
            backend:
              service:
                name: thingz-backend
                port:
                  number: 8080
          - path: /
            pathType: Prefix
            backend:
              service:
                name: thingz-frontend
                port:
                  number: 3000

