apiVersion: v1
kind: Secret
metadata:
  name: thingz-secrets
  namespace: thingz
type: Opaque
stringData:
  DB_PASSWORD: "replace-me"
  JWT_SECRET: "replace-with-64-plus-char-secret"
  KAKAO_CLIENT_ID: "replace-me"
  KAKAO_CLIENT_SECRET: "replace-me"
  AWS_ACCESS_KEY: "replace-me"
  AWS_SECRET_KEY: "replace-me"
  S3_BUCKET: "replace-me"
  OPENAI_API_KEY: "replace-me"

